### ISSUE TITLE
Composer version differs from this repository

### ISSUE THREAD

**Issue by pawelkaczmarek** [mexitek/phpColors#27]
I might be wrong, but I couldn't manage to get the code from composer that would match this repository. I tried "composer require mexitek/phpColors".

It's not much of an issue with the library, which is great, but I think someone should have a look at it.

**Comment by thedavidmeister** [comment]
Try 'composer require mexitek/phpcolors dev-master'

**Comment by pawelkaczmarek** [comment]
Bingo! Thanks for a hint.

**Comment by thedavidmeister** [comment]
Cool, I added a PR with docs referencing that command.

**Comment by thedavidmeister** [comment]
Hi, sorry to re-open, but the issue with using `dev-master` is that you end up with a `.git` folder coming down with the code. This isn't always desirable, such as when wanting to directly commit composer libraries into a parent repo.

I think the simplest fix here is to simply tag the latest commit as a release so that it comes down with a more normal `composer.json` setup.
